-   id: prepare-commit-msg
    name: prepare-commit-msg
    description: Add help in commit message
    entry: prepare_commit_msg
    stages: [prepare-commit-msg]
    language: python
-   id: check_commiter_domain
    name: check_commiter_domain
    description: Check domain of commiter as per config
    entry: check_commiter_domain
    stages: [pre-commit]
    language: python
- id: pretty-format-java
  name: Google Java Formatter
  description: Runs Google Java Formatter over Java source files
  entry: pretty-format-java
  stages: [pre-commit]
  language: python
  types: [java]
  # this is needed because the hook downloads google-java-formatter and
  # we don't have yet a nice way of ensuring a single download over multiple runs
  require_serial: true
  minimum_pre_commit_version: '1'